### ISSUE TITLE
Is there any method that can be used to obtain adjusted P values

### ISSUE THREAD

**Issue by sherryfan030** [precimed/pleiofdr#24]
Hi there,

Thank you for the excellent work in developing tools.

I have a question: Generally, based on a set of SNPs with P-values, adjusted-P values can be produced using the FDR method.

However, for conditional FDR derived from a bivariate Gaussian distribution model, as referenced, is there any method that can be used to obtain adjusted-P values?

Best regards,

Sherry

**Comment by sherryfan030** [comment]
I solved the problem. Thanks.

**Comment by dxy257** [comment]
Hi, could you please share how you solved this issue? Thank you!
