### ISSUE TITLE
No pvalue from ldsc

### ISSUE THREAD

**Issue by XaviFar** [precimed/pleiofdr#6]
In the python_convert there is the options to convert LDSC results from munge into mat files, but when I try to run the pleioFDR it returns an error saying that there is no p-value column.
Is there a way to solve this?

thanks

**Comment by ofrei** [comment]
@XaviFar 
Good point! I've added ``sumstats.py pvalue --sumstats <input> --out <output>``  - this command will add PVAL column from Z column. If Z is not available it will search for BETA and SE, and assume Z=BETA/SE to calculate PVAL.
I haven't got time to test this thoroughly, please let me know if you see any issues!

**Comment by XaviFar** [comment]
Awesome! Thanks for the fast solution.
