### ISSUE TITLE
Gene name missing

### ISSUE THREAD

**Issue by XaviFar** [precimed/pleiofdr#7]
After following the tutorial, the gene field from the output is empty, am I missing a file or a flag to get this?

**Comment by FernandaSantos13** [comment]
Same here. Could you solve that?

**Comment by ofrei** [comment]
Hi. We deliberately removed genename because there are many way to annotate SNPs to genes, and it's best to use external tools (e.g. https://fuma.ctglab.nl/ ) for this task.

**Comment by FernandaSantos13** [comment]
Hi Alex, 
I see. Thank you so much!
